# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password') if Rails.env.development?

CategoryProducts.destroy_all
CategoryProducts.create(name: "Motores")
CategoryProducts.create(name: "Moda")
CategoryProducts.create(name: "Electrónica")
CategoryProducts.create(name: "Colleccionables y Arte")
CategoryProducts.create(name: "Hogar y Jardín")
CategoryProducts.create(name: "Deporte")
CategoryProducts.create(name: "Juguetes y Pasatiempos")
CategoryProducts.create(name: "Empresarial e Industrial")
CategoryProducts.create(name: "Música")
CategoryProducts.create(name: "Partes y Accesorios", category_product_id: CategoryProducts.find_by(name: "Motores").id)
CategoryProducts.create(name: "Vehículos", category_product_id: CategoryProducts.find_by(name: "Motores").id)
CategoryProducts.create(name: "Belleza", category_product_id: CategoryProducts.find_by(name: "Moda").id)
CategoryProducts.create(name: "Carteras y Accesorios", category_product_id: CategoryProducts.find_by(name: "Moda").id)
CategoryProducts.create(name: "Salud", category_product_id: CategoryProducts.find_by(name: "Moda").id)
CategoryProducts.create(name: "Joyería", category_product_id: CategoryProducts.find_by(name: "Moda").id)
CategoryProducts.create(name: "Niños y Bebé", category_product_id: CategoryProducts.find_by(name: "Moda").id)
CategoryProducts.create(name: "Ropa para Hombre", category_product_id: CategoryProducts.find_by(name: "Moda").id)
CategoryProducts.create(name: "Zapatos", category_product_id: CategoryProducts.find_by(name: "Moda").id)
CategoryProducts.create(name: "Relojes", category_product_id: CategoryProducts.find_by(name: "Moda").id)
CategoryProducts.create(name: "Ropa para Mujer", category_product_id: CategoryProducts.find_by(name: "Moda").id)
CategoryProducts.create(name: "Cámara y Fotografía", category_product_id: CategoryProducts.find_by(name: "Electrónica").id)
CategoryProducts.create(name: "Electrónica Automotriz", category_product_id: CategoryProducts.find_by(name: "Electrónica").id)
CategoryProducts.create(name: "Celulares y Accesorios", category_product_id: CategoryProducts.find_by(name: "Electrónica").id)
CategoryProducts.create(name: "Computadoras y Tablets", category_product_id: CategoryProducts.find_by(name: "Electrónica").id)
CategoryProducts.create(name: "TV, Video y Audio", category_product_id: CategoryProducts.find_by(name: "Electrónica").id)
CategoryProducts.create(name: "Videojuegos y Consolas", category_product_id: CategoryProducts.find_by(name: "Electrónica").id)
CategoryProducts.create(name: "Antiguedades", category_product_id: CategoryProducts.find_by(name: "Colleccionables y Arte").id)
CategoryProducts.create(name: "Arte", category_product_id: CategoryProducts.find_by(name: "Colleccionables y Arte").id)
CategoryProducts.create(name: "Monedas y Papel Moneda", category_product_id: CategoryProducts.find_by(name: "Colleccionables y Arte").id)
CategoryProducts.create(name: "Coleccionables", category_product_id: CategoryProducts.find_by(name: "Colleccionables y Arte").id)
CategoryProducts.create(name: "Comics", category_product_id: CategoryProducts.find_by(name: "Colleccionables y Arte").id)
CategoryProducts.create(name: "Muñecas y Osos", category_product_id: CategoryProducts.find_by(name: "Colleccionables y Arte").id)
CategoryProducts.create(name: "Coleccionables del Entretenimiento", category_product_id: CategoryProducts.find_by(name: "Colleccionables y Arte").id)
CategoryProducts.create(name: "Cerámica y Vidrio", category_product_id: CategoryProducts.find_by(name: "Colleccionables y Arte").id)
CategoryProducts.create(name: "Coleccionables del Deporte", category_product_id: CategoryProducts.find_by(name: "Colleccionables y Arte").id)
CategoryProducts.create(name: "Estampillas", category_product_id: CategoryProducts.find_by(name: "Colleccionables y Arte").id)
CategoryProducts.create(name: "Bebé", category_product_id: CategoryProducts.find_by(name: "Hogar y Jardín").id)
CategoryProducts.create(name: "Baño", category_product_id: CategoryProducts.find_by(name: "Hogar y Jardín").id)
CategoryProducts.create(name: "Cama", category_product_id: CategoryProducts.find_by(name: "Hogar y Jardín").id)
CategoryProducts.create(name: "Artesanía", category_product_id: CategoryProducts.find_by(name: "Hogar y Jardín").id)
CategoryProducts.create(name: "Comida y Bebestibles", category_product_id: CategoryProducts.find_by(name: "Hogar y Jardín").id)
CategoryProducts.create(name: "Muebles", category_product_id: CategoryProducts.find_by(name: "Hogar y Jardín").id)
CategoryProducts.create(name: "Decoración", category_product_id: CategoryProducts.find_by(name: "Hogar y Jardín").id)
CategoryProducts.create(name: "Reforma Hogareña", category_product_id: CategoryProducts.find_by(name: "Hogar y Jardín").id)
CategoryProducts.create(name: "Quehaceres y Organización", category_product_id: CategoryProducts.find_by(name: "Hogar y Jardín").id)
CategoryProducts.create(name: "Cocina y Comedor", category_product_id: CategoryProducts.find_by(name: "Hogar y Jardín").id)
CategoryProducts.create(name: "Electrodomésticos", category_product_id: CategoryProducts.find_by(name: "Hogar y Jardín").id)
CategoryProducts.create(name: "Suministros para Mascotas", category_product_id: CategoryProducts.find_by(name: "Hogar y Jardín").id)
CategoryProducts.create(name: "Herramientas", category_product_id: CategoryProducts.find_by(name: "Hogar y Jardín").id)
CategoryProducts.create(name: "Jardín", category_product_id: CategoryProducts.find_by(name: "Hogar y Jardín").id)
CategoryProducts.create(name: "Boxeo, Artes Marciales y MMA", category_product_id: CategoryProducts.find_by(name: "Deporte").id)
CategoryProducts.create(name: "Ciclismo", category_product_id: CategoryProducts.find_by(name: "Deporte").id)
CategoryProducts.create(name: "Pesca", category_product_id: CategoryProducts.find_by(name: "Deporte").id)
CategoryProducts.create(name: "Entrenamiento y Correr", category_product_id: CategoryProducts.find_by(name: "Deporte").id)
CategoryProducts.create(name: "Golf", category_product_id: CategoryProducts.find_by(name: "Deporte").id)
CategoryProducts.create(name: "Caza", category_product_id: CategoryProducts.find_by(name: "Deporte").id)
CategoryProducts.create(name: "Juegos de Interior", category_product_id: CategoryProducts.find_by(name: "Deporte").id)
CategoryProducts.create(name: "Deportes al Aire Libre", category_product_id: CategoryProducts.find_by(name: "Deporte").id)
CategoryProducts.create(name: "Deportes de Equipos", category_product_id: CategoryProducts.find_by(name: "Deporte").id)
CategoryProducts.create(name: "Deportes Acuáticos", category_product_id: CategoryProducts.find_by(name: "Deporte").id)
CategoryProducts.create(name: "Deportes de Invierno", category_product_id: CategoryProducts.find_by(name: "Deporte").id)
CategoryProducts.create(name: "Yoga y Pilates", category_product_id: CategoryProducts.find_by(name: "Deporte").id)
CategoryProducts.create(name: "Figuras de Acción", category_product_id: CategoryProducts.find_by(name: "Juguetes y Pasatiempos").id)
CategoryProducts.create(name: "Juguetes de Construcción", category_product_id: CategoryProducts.find_by(name: "Juguetes y Pasatiempos").id)
CategoryProducts.create(name: "Vehículos de Juguete", category_product_id: CategoryProducts.find_by(name: "Juguetes y Pasatiempos").id)
CategoryProducts.create(name: "Educacional", category_product_id: CategoryProducts.find_by(name: "Juguetes y Pasatiempos").id)
CategoryProducts.create(name: "Juegos", category_product_id: CategoryProducts.find_by(name: "Juguetes y Pasatiempos").id)
CategoryProducts.create(name: "Modelos de Trenes", category_product_id: CategoryProducts.find_by(name: "Juguetes y Pasatiempos").id)
CategoryProducts.create(name: "Kits y Modelos", category_product_id: CategoryProducts.find_by(name: "Juguetes y Pasatiempos").id)
CategoryProducts.create(name: "Juguetes de Pre-escolar", category_product_id: CategoryProducts.find_by(name: "Juguetes y Pasatiempos").id)
CategoryProducts.create(name: "Radiocontrol", category_product_id: CategoryProducts.find_by(name: "Juguetes y Pasatiempos").id)
CategoryProducts.create(name: "Juguetes de TV, Películas y Personajes", category_product_id: CategoryProducts.find_by(name: "Juguetes y Pasatiempos").id)
CategoryProducts.create(name: "Cartas Intercambiables", category_product_id: CategoryProducts.find_by(name: "Juguetes y Pasatiempos").id)
CategoryProducts.create(name: "Agricultura y Silvicultura", category_product_id: CategoryProducts.find_by(name: "Empresarial e Industrial").id)
CategoryProducts.create(name: "Construcción", category_product_id: CategoryProducts.find_by(name: "Empresarial e Industrial").id)
CategoryProducts.create(name: "Equipo ELéctrico y de Testeo", category_product_id: CategoryProducts.find_by(name: "Empresarial e Industrial").id)
CategoryProducts.create(name: "Gasolina y Energía", category_product_id: CategoryProducts.find_by(name: "Empresarial e Industrial").id)
CategoryProducts.create(name: "Oficina", category_product_id: CategoryProducts.find_by(name: "Empresarial e Industrial").id)
CategoryProducts.create(name: "Ciencias de la Salud y Laboratorio", category_product_id: CategoryProducts.find_by(name: "Empresarial e Industrial").id)
CategoryProducts.create(name: "Maquinaria Pesada", category_product_id: CategoryProducts.find_by(name: "Empresarial e Industrial").id)
CategoryProducts.create(name: "Automatización Industrial y Control", category_product_id: CategoryProducts.find_by(name: "Empresarial e Industrial").id)
CategoryProducts.create(name: "Maquinaria Ligera y Herramientas", category_product_id: CategoryProducts.find_by(name: "Empresarial e Industrial").id)
CategoryProducts.create(name: "Suministros Industriales", category_product_id: CategoryProducts.find_by(name: "Empresarial e Industrial").id)
CategoryProducts.create(name: "Manofactura y Metalurgia", category_product_id: CategoryProducts.find_by(name: "Empresarial e Industrial").id)
CategoryProducts.create(name: "Embalaje y Envio", category_product_id: CategoryProducts.find_by(name: "Empresarial e Industrial").id)
CategoryProducts.create(name: "Impresión y Artes Gráficas", category_product_id: CategoryProducts.find_by(name: "Empresarial e Industrial").id)
CategoryProducts.create(name: "Restaurante y Servicio de Comidas", category_product_id: CategoryProducts.find_by(name: "Empresarial e Industrial").id)
CategoryProducts.create(name: "Comercio y Servicios", category_product_id: CategoryProducts.find_by(name: "Empresarial e Industrial").id)
CategoryProducts.create(name: "Sitios y Negocios a la Venta", category_product_id: CategoryProducts.find_by(name: "Empresarial e Industrial").id)
CategoryProducts.create(name: "Instrumentos Musicales y Equipo", category_product_id: CategoryProducts.find_by(name: "Música").id)
CategoryProducts.create(name: "Música Grabada", category_product_id: CategoryProducts.find_by(name: "Música").id)
CategoryProducts.create(name: "Entradas y Experiencias", category_product_id: CategoryProducts.find_by(name: "Música").id)



create_table "category_products", force: :cascade do |t|
  t.string "name"
  t.bigint "category_product_id"
  t.datetime "created_at", null: false
  t.datetime "updated_at", null: false
  t.index ["category_product_id"], name: "index_category_products_on_category_product_id"
end

create_table "category_services"
